# Change these first
owner: recmanj # Your GitHub organization or username, where this repository lives
repo: eodh-status # The name of this repository

sites:
  - name: Earth Observation DataHub 
    url: https://eodatahub.org.uk
  - name: EODH Workflows
    url: https://eodatahub.org.uk/api/docs/workflow-runner/ping
  - name: EODH Commercial API
    url: https://eodatahub.org.uk/api/catalogue/manage/health
  - name: EODH STAC API
    url: https://eodatahub.org.uk/api/catalogue/stac/_mgmt/ping
  - name: EODH TiTiler API
    url: https://eodatahub.org.uk/titiler/healthz
  - name: EODH Jupyter Hub
    url: https://eodatahub-workspaces.org.uk/healthz

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /eodh-status
  logoUrl: https://eodatahub.org.uk/static/img/menu/favicon.901b0f6b283d.svg
  name: EODH Status
  introTitle: "**Earth Observation DataHub status page"
  introMessage: Status page monitoring EO DataHub site and relevant APIs
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
